#server
server:
  port: 8088
  session:
    timeout: 3600 #秒
  context-path: /

#spring
spring:
  #datasource
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/springboot2?useUnicode=true&characterEncoding=utf8
#    username: root
#    password: xwbing
  #jpa
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate :
        naming-strategy : org.hibernate.cfg.ImprovedNamingStrategy
        dialect : org.hibernate.dialect.MySQL5Dialect
  #aop
  aop:
    auto: true # Add @EnableAspectJAutoProxy
    proxy-target-class: false
  #mail
  mail:
    host: smtp.163.com
    username: xwb1ng@163.com
    password: xwbing000111 #邮箱设置里获取的授权码
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          auth: true #授权
          starttls:
            enable: true
            required: true
  #编码
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  #消息队列
  rabbitmq:
     host: 127.0.0.1
     port: 5672
     username: root
     password: xwbing
     virtual-host: /control
     connection-timeout: 60000 #毫秒
     publisher-confirms: true #支持发布确认
     publisher-returns: true #支持发布返回
     cache:
       channel:
         size: 1
#log
logging:
  config: classpath:log4j2.xml

